
pipeline {
  agent any
  stages {
    stage('Clone') {
      steps {
        git 'https://github.com/Anwesha-web/devops-infra-project.git'
      }
    }
    stage('Build Docker') {
      steps {
        sh 'docker build -t your-dockerhub-username/flask-app:latest app/'
      }
    }
    stage('Push Docker') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
          sh """
            echo "$PASS" | docker login -u "$USER" --password-stdin
            docker push your-dockerhub-username/flask-app:latest
          """
        }
      }
    }
    stage('Deploy to EKS') {
      steps {
        sh 'kubectl apply -f k8s/'
      }
    }
  }
}
